name: On Push (Master)

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    uses: moonstar-x/react-twitch-embed/.github/workflows/pr.yml@master

  docs-deploy:
    name: Build Docs & Deploy
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Documentation
        run: npm run storybook:build

      - name: Publish Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          external_repository: moonstar-x-docs/react-twitch-embed
          publish_branch: gh-pages
          publish_dir: ./docs-build
          enable_jekyll: false
          allow_empty_commit: true
          commit_message: ${{ github.event.head_commit.message }}

  build-publish:
    name: Build & Publish to NPM
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Deploy to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
